endroid/qr-code

- src/Endroid/QrCode/Exceptions/MissingFontPathException.php
- src/Endroid/QrCode/QrCode.php
Adds support for including a label underneath the QR Code directly in the image PNG. It requires that the user set the label text and TTF font path at a minimum, and also optionally supports changing the font size away from the default of 12px, for example:
```
use Endroid\QrCode\QrCode;
$qrCode = new QrCode();
$qrCode
->setText("Life is too short to be generating QR codes")
->setSize(300)
->setPadding(10)
->setErrorCorrection('high')
->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
->setFontPath('path/to/yourfont.ttf')
->setFontSize(16)
->setLabel('image label')
->render()
;
```
Note that at the moment, the code does not handle any sort of word wrapping. If the label string or font size is too …
> Preliminary support for embedding text labels underneath QR Code image

- src/QrCode.php
This change allows you to use transparency in your logo (if you for example use an png image)
> Allow transparency in logos

- src/QrCode.php
Previously, output image was always enlarged by quiet zone region, no matter if $draw_quiet_zone is true or false.
> Fixes handling of $draw_quiet_zone parameter (#67)

- README.md
- composer.json
- src/Bundle/QrCodeBundle/Controller/QrCodeController.php
- src/Bundle/QrCodeBundle/Resources/config/routing.yml
- tests/Bundle/app/AppKernel.php
- tests/Bundle/app/bootstrap.php
- tests/Bundle/app/config/routing.yml
I find it kind of strange that the Sensio Framework Extra Bundle is required as a dependency for this bundle. It's only used for two things: routing (which is better done with a routing file anyway) and auto-rendering a simple template. It may make it slightly convenient there, but there are several disadvantages:
- You need the bundle to load the annotation routes, but this is not documented anywhere.
- The bundle brings an unnecessary amount of dependencies, requires special handling before tests (loading the Doctrine Annotation registry), etc.
- In projects where you don't want to (or sometimes cannot) use the bundle you have to write the routing file or even the whole controller yourself.
Which is why I decided to remove it in our fork. This makes it easier to use the QrCode routes …
> Remove dependency on Sensio Framework Extra Bundle

- composer.json
- phpunit.xml.dist
- src/Twig/Extension/QrCodeExtension.php
- src/Twig/Extension/QrCodeUriExtension.php
- tests/Twig/Extension/QrCodeExtensionTest.php
- tests/Twig/Extension/QrCodeUriExtensionTest.php
This PR adds 
- Some missing dev dependencies
- Adds the phpunit bridge for deprecations
- Suggests twig (and conflicts with incompatible twig versions)
- Deprecated the QrCodeExtension
- Added the QrCodeUriExtension
- The QrCodeRoutingExtension will be added to the bundle as it would otherwise cause a circular dependency between the packages (due to route names).
Closes #142.
> Split of the twig extension

- composer.json
Latest symfony packages required php 7, which conflicts with QrCode 2.* branch php requirement and doesn't install on systems with php5.
Using ^ version selector instead.
> Branch 2.* "symfony/*" version >=2.7 installs latest symfony packages

- src/Writer/PngWriter.php
Some more places where `imagecopyresampled` must receive an integer, but data might be double when using `roundBlockSize = false`.
> Force integer params in imagecopyresampled

- src/QrCode.php
- tests/QrCodeTest.php
`$qrCode->setWriterByExtension()` does not work (fails with `Call to a member function getWriters() on null`) unless the `writerRegistry` is created first.
Based on the other usage within the class, I'd say the corresponding call could be moved to the constructor.
This pr changes this behaviour and provides tests (which fail on current master).
> Move createWriterRegistry to constructor of QrCode

- src/ErrorCorrectionLevel.php
- src/LabelAlignment.php
This adds method hints for enums to allow static code analysis or inspection to work properly.
Thanks
> Add enum method hints to enable static analysis

- composer.json
https://symfony.com/blog/cve-2020-5255-prevent-cache-poisoning-via-a-response-content-type-header
> Security Check

- src/QrCode.php
- src/QrCodeInterface.php
- src/Writer/SvgWriter.php
This PR is kind of a bugfix, kind of an enhancement.
**Background:**
In https://github.com/endroid/qr-code/pull/173 the functionality to add logo in svg qr codes was added. The `xlink:href` attribute was used to add the embedded image (see [SvgWriter.php#L53](https://github.com/Woodehh/qr-code/blob/master/src/Writer/SvgWriter.php#L53)).
But `SimpleXML` turns the `xlink:href` attribute into a `href` attribute, as [this blog post ](https://blog.jondh.me.uk/2010/10/resetting-namespaced-attributes-using-simplexml/)from 10 years ago(!) already stated. So far so good, because in SVG `xlink:href` [is actually deprecated](https://www.w3.org/TR/SVG2/linking.html#XLinkRefAttrs).
Yet there is a catch: If you put an svg-qrcode with an embedded logo into a pdf, the `xlink:href` attribute is expected. …
> Add option to force xlink:href when adding logos in svg

- README.md
- src/QrCode.php
- tests/QrCodeTest.php
I keep struggling with how `roundBlockSize()` works. Adding additional margin is rarely what I want, because it makes it impossible to know the actual size of the qr code contents.
Therefore this pr introduces a new way to handle this, with `round block size modes`:
```php
// Current method usage – nothing changes here in behaviour
$qrCode->setRoundBlockSize(true);
// Current method usage, with explicit mode property – nothing changes here in behaviour
$qrCode->setRoundBlockSize(true, QrCode::ROUND_BLOCK_SIZE_MODE_MARGIN); 
// New mode ENLARGE: The size of the qr code and the final image is enlarged, if necessary
$qrCode->setRoundBlockSize(true, QrCode::ROUND_BLOCK_SIZE_MODE_ENLARGE);
// New mode SHRINK: The size of the qr code and the final image is shrinked, if necessary …
```
> Add mode options for roundBlockSize

- src/Writer/PngWriter.php
if alpha channel is set to 0. An alpha channel is only added, if this value is between 1 and 127 (higher value than 127 is not allowed by php).
I created an issue before and decided to provide a pull request for this: https://github.com/endroid/qr-code/issues/264
> Added an exception to allow non alpha png files written

- src/Writer/SvgWriter.php
When multiple QR codes are output inline SVG in HTML, the first <rect id="block"> will overwrite the next SVG <rect id="block">.
I used WriterOptions to get around it.
Test code:
https://gist.github.com/tohokuaiki/c4729c7bf1b204de339d5c8d54934d2d
> add SvgWriter option for xlink:href

- composer.json
- src/Writer/PngWriter.php
I know this isn't recommended at all (#182), but this adds support for Symfony 3.x if on older setups if you need something bridging until shifting up to a newer version.
> Add Symfony 3.x compatibility for 2.x

- src/Builder/Builder.php
- src/Builder/BuilderInterface.php
- src/ImageData/LogoImageData.php
- src/Logo/Logo.php
- src/Logo/LogoInterface.php
- src/Writer/PngWriter.php
Currently if you want to use a logo with transparency on top of a QR code the QR code will show through, this "punches out" a hole in the QR code the size of the logo.
> Implements logo background punchout functionality

- src/Writer/SvgWriter.php
This missing namespace causes the logo to not appear when embedding the qr code in a pdf.
> Add missing namespace for xlink logo in SvgWriter

- src/ImageData/LogoImageData.php
PHP Version: 8.1.0
Problem:
When added some png files as a logo, it will throw a warning like this:
`PHP Warning:  imagecreatefromstring(): gd-png: libpng warning: iCCP: known incorrect sRGB profile`
In some php frameworks, they treated it as an exception which end the program immediately and cannot generate the qr code.
Related issue:
https://github.com/dompdf/dompdf/issues/2718
Reproduce:
```php
<?php
$data = file_get_contents("https://user-images.githubusercontent.com/1336778/167459293-12d01436-33ac-432d-b8a1-fac00ef113c1.png");
// Error!!
$im = imagecreatefromstring($data);
// Fix
// $im = @imagecreatefromstring($data);
if ($im !== false) {
echo "OK";
} else {
echo "Not OK";
}
```
> Suppress unexpected libpng warning when added a logo

- src/Color/Color.php
- src/Color/ColorInterface.php
Add simple getter to have a hex of Color. 
**_E.G :_** 
- $color = new Color(255, 0, 0);
- $color->getHex() // return '#ff0000'
> Add hex getter to Color

- src/ImageData/LogoImageData.php
If a web server (such as LiteSpeed) sends lowercase header parameter names, this triggers an exception. By changing all parameter names to lower case, we avoid this problem.
> Bugfix: Lower-case HTTP header parameters

- src/Builder/BuilderInterface.php
In version 6 all methods in `Endroid\QrCode\Builder\Builder` were refactored towards arguments, either in the constructor or in the `build` method. To allow the interface to be compatible, this MR adds the arguments to the `build` method in the interface.
> Add optional arguments to interface, to enhance compatibility

- src/Exception/BlockSizeTooSmallException.php
- src/Matrix/Matrix.php
Hello! It would be great to make this Exception more specific. So it can be caught and do something with it. In my case, I can return an error to the front end.
P.S. The name doesn't matter.
> Add BlockSizeTooSmallException
